### ISSUE TITLE
High CPU usage when a lot of tabs are open

### ISSUE THREAD

**Issue by fifaltra** [proginosko/LeechBlockNG#53]
First of all thank you for your great extension, and for porting it to webextensions. 

I usually have a lot of tabs (think hundreds) open and LeechblockNG uses about 10 to 15 percent of my CPU when the browser is just idling. In the old version I investigated this and found that Leechblock constantly cycled through all open tabs checking whether they should be blocked. I came up with a hack that made Leechblock just check the tab that is actually in focus which reduced the CPU usage to unnoticable levels and was happy. This had the nice side effect that tabs in the background would not get blocked. Clicking back 20 tabs from the same group after the block is lifted is quite annoying. But now I'm not sure if I can do this and install the modified extension, so I thought I'd try the official way. 

I guess LeechblockNG also goes through all tabs which causes the high CPU usage. Maybe you could provide an option to choose between "block tabs on focus" and "block tabs also in background". I am not sure if some users are relying on tabs in the background also being blocked (for example for media playback). 

If you plan to implement this, there is one thing that was an issue in the way I implemented it in the old version. So you should probably watch out for this behaviour:
The hack I used made it possible to circumvent the block by middle clicking on a link to open in new tab, let it load in the background and then switching to the new tab afterwards. This way the tab would not get blocked if "immediately block sites" was not enabled. This might be an issue for some users, because that way you can click from one page to the next for example on a news site way past the blocking time. I did not find a better way of doing this, but maybe you find one.

**Comment by fifaltra** [comment]
I fixed this now in my own version, it was surprisingly easy and does not even have the problem that I had with the old version of leechblock. As far as I tested, this does not break anything and reduces the cpu usage to unnoticable levels. This is the diff, in case anyone wants to implement it for themselves:

221c221 (in function processTabs() )
><     browser.tabs.query({currentWindow: true, active: true}).then(onGot, onError);
---
>       browser.tabs.query({}).then(onGot, onError);

1057,1070c1057 (in function  handleTabActivated(activeInfo) )


><     
><     browser.tabs.get(activeInfo.tabId).then(onGot, onError);
><     
><     function onGot(tab) {
><         let blocked = checkTab(tab.id, tab.url, false);                                                                                                                                                                        
><                                                                                                                                                                                                                                
><         if (!blocked) {                                                                                                                                                                                                        
><           updateTimer(tab.id);                                                                                                                                                                                                 
><         }                                                                                                                                                                                                                      
><     }                                                                                                                                                                                                                          
><                                                                                                                                                                                                                                
><     function onError(error) {                                                                                                                                                                                                  
><       warn("Cannot get tabs: " + error);                                                                                                                                                                                       
><     }                                                                                                                                                                                                                          
---                                                                                                                                                                                                                              
>       updateTimer(activeInfo.tabId);               `  

Here's the file as a whole:
[backgroundjs.txt](https://github.com/proginosko/LeechBlockNG/files/1957981/backgroundjs.txt)
(Had to change the file ending because it wouldn't upload otherwise)

**Comment by fergalt** [comment]
I can confirm this appears to work: I had encountered the same issue on the chrome version (https://github.com/proginosko/LeechBlockNG-chrome), hitting 5-10% cpu usage for the plugin, when multiple tabs were open.

Porting the changes into the Chrome extension format worked well, dropping the CPU usage associated with the extension 0.1-0.6%.

**Comment by proginosko** [comment]
Thanks for this, guys!

I hesitate to implement this as the default behavior, because some users will still expect/want non-active tabs to be immediately blocked when the blocking conditions are met, plus it may have side-effects I haven't thought about. So I'm going to implement it as an option instead. Look out for it in the next release.

**Comment by fifaltra** [comment]
I found some side-effects in the meantime, which I did not notice with the block sets I initially tested:

1. If you activate one tab, then switch to another tab, and then switch back to the old tab, time will be counted as if you were on the first tab the whole time plus the time spent on the second tab. (I have a fix for this, will upload later today)

2. If you have firefox open, then lock your screen, then unlock it, the time the screen was locked is counted as "spent on this page" somehow. I am not sure how to fix this, short of putting a check before adding times (like discard secsopen if secsopen > 2*(checking interval)). If I have time, I will look into this a bit more. Maybe this is also an OS issue, I'm on Kubuntu.

**Comment by proginosko** [comment]
The first issue I discovered myself and fixed in the v0.9.1 release (see function handleTabActivated). I'm not sure about the second, but try the new version and see if it's still an issue.

**Comment by fifaltra** [comment]
That was fast :) Thanks a lot! 
I can't reproduce the second issue with version 0.9.1 right now, so maybe you did something that fixed it.

**Comment by fifaltra** [comment]
i was on one page, the timer counted down and it was blocked and all was fine. 

Then I clicked a link from an email, which put the browser window in focus. The browser tried to open the tab, and then suddenly all other tabs that were open in the background started displaying that there was some loading going on in them, the CPU went up to 25% and after some time, all tabs that were in the block set were blocked.

This took about 10 seconds during which time the browser did not react to anything. I guess this happened because in handletabactivated all tabs get processed. But I'm not sure how to fix this without breaking something else. This is probably why the second issue is fixed in your implementation.

**Comment by proginosko** [comment]
All tabs have to be processed eventually to keep track of time spent on sites. With the new setting checked, tabs are processed whenever a tab is activated. I'm surprised it hung your browser for 10 secs though. How many tabs did you have open?

I have some ideas about how to further streamline the tab-checking process. Stay tuned...

**Comment by fifaltra** [comment]
I have about 300 tabs open and I have a block set "*" that just blocks everything after 45 min per hour, so it wasn't just the checking but also the fact that every tab had to load the "site blocked" page...

The way I fixed issue 1 before was like this:

     function handleTabActivated(activeInfo) {                                              
        log("handleTabActivated: " + activeInfo.tabId);                                

        let focus = (!gFocusWindowId || activeInfo.windowId == gFocusWindowId);        
                                                                                       
        let id = activeInfo.tabId;                                                         
        if (gTabs[id]) {                                                                   
          gTabs[id].openTime = undefined;                                                  
          gTabs[id].focusTime = undefined;                                                 
        }                                                                                  
        clockPageTime(activeInfo.tabId, true, focus);                                  
                                                                                       
        browser.tabs.get(activeInfo.tabId).then(onGot, onError);                           
                                                                                       
        function onGot(tab) {                                                              
          let blocked = checkTab(tab.id, tab.url, false);                                
                                                                                       
          if (!blocked) {                                                                
            updateTimer(tab.id);                                                         
          }                                                                              
        }                                                                                  
                                                                                       
        function onError(error) {                                                          
           warn("Cannot get tabs: " + error);                                               
        }                                                                                  
    }                          

That way, checking all tabs can be avoided. But then one has to think about a way to fix issue 2...

**Comment by proginosko** [comment]
I suspect a lot of the processing is due to creating the regexps used to check the URLs. I've rewritten the code so that the regexps are only (re)created when the options are changed. (Should have done that a long time ago!)

If you want to try a signed beta version, you can download it here:

http://www.proginosko.com/files/lbng/leechblock_ng-0.9.3b1-an+fx.xpi

If you try it, let me know if you see any improvement.

**Comment by Metaception** [comment]
> If you activate one tab, then switch to another tab, and then switch back to the old tab, time will be counted as if you were on the first tab the whole time plus the time spent on the second tab. (I have a fix for this, will upload later today)

I am still getting this issue on 0.9.3.1, I believe this is due to conflicts between:
- Count time spent on these sites only when browser tab is active
- Process only active tabs

With one/zero of these enabled, the results are as expected. When you enable both you get the double time spent bug.

I can't disable **Count time spent on these sites only when browser tab is active** because it stops the time from being counted when the windows loses focus, see #49.

**Comment by vandenoever** [comment]
Leechblock 0.9.3.1 in Firefox 59 with ~50 tabs open uses ~15% cpu. I'm not interested in counting time spent in sites, but want sites blocked at certain times. That should not require constant monitoring of all tabs. Enabling 'Process only active tabs' reduces the firefox CPU use to ~ 3%.

**Comment by TomSwiss** [comment]
Firstly, thanks for all your work on this great extension!
I was having this issue on Firefox for Linux, with the CPU usage for the main firefox process and the WebExtensions process both sometimes getting up near 100% of a core each.  The frustration was extreme, but after tracking it down to LeechBlock, finding this thread, and then enabling 'Process only active tabs', it's a miracle cure! I've got my computer back again.

I'd like to suggest that the option be more prominently recommended for us heavy tabs users.

Thanks again.

**Comment by jotaf98** [comment]
Hi, thanks for adding this option; it turned out that LeechBlock was quite a battery drain and I almost changed to a different addon before stumbling across this option.

I understand the reasoning for not making this the default behavior. However, since this may affect other unsuspecting users, may I suggest showing a message (with an option to not show it again) when there are many tabs opened to explain the two options? I realize that's a fair amount of UI work but just wanted to put it out there.

A (probably much simpler) way to deal with it is to just not check the tabs so frequently, which can be done depending on the granularity of the time limits. For example, if I want to block something after 5 minutes, this check can probably be done every 10 seconds, since I don't mean that I want to block exactly after 5 minutes and 0 seconds. If I want to block sites after 45 minutes, then the checks can probably be done on the granularity of 1 minute and it won't make a difference.

This may save a lot of CPU in most situations. I guess the granularity (timer interval) could be set as a percentage of the time limit, or something like that.

**Comment by proginosko** [comment]
I finally tracked down the performance-killing code and zapped it. You should find performance _vastly_ improved in v0.9.11 (without having to select "Process only active tabs"). Let me know how it works for you.

You can monitor the performance via **about:performance**. LB should now show low energy impact.

**Comment by jotaf98** [comment]
Yes, it seems much better than before! Thanks!

**Comment by proginosko** [comment]
Okay, good. I'm going to close this issue for now.
