### ISSUE TITLE
Blocking sites "until the end of time" after expiration of designated block period

### ISSUE THREAD

**Issue by kontramantra** [proginosko/LeechBlockNG#62]
I'm using Firefox 59.0.2 on Windows 7.

I have two Block Sets. One is for permanent blocking (0000-2400, all days), and the other for 0000-2100, all days, which I made just yesterday morning. Later in the evening, the sites from the second block have been blocked until 21h as expected (i.e. showing the Leechblock NG default page). After I refreshed the pages after 21h, the expiration time changed from "The page will be blocked until 21:00" into " The page will be block untik the end of time", instead of showing the desired page.

I suspected that maybe "0000" was the issue, so I changed it to "0001", but still got the same results. I'm not sure if, for some reason, Block Set 2 falls through to Block Set 1. I have no idea, just guessing.

Is there a config file I should upload to help you debug?

Thank you.

Edit: clarity

**Comment by proginosko** [comment]
Please export your settings to a text file and email it to me (leechblockng@proginosko.com).

**Comment by proginosko** [comment]
Sorry for the delay in replying. I tested the settings you sent and it works fine for me, so I'm at a loss to explain why you're getting that problem. I suggest uninstalling and reinstalling LB, then importing the settings you sent me, and see if that resolves the issue.

**Comment by sargon2** [comment]
Just ran into this and it was caused by hitting refresh on the "blocked" page.  That just refreshes the blocked page.  If you hit back instead of refresh it exits the block fine.

**Comment by alphestdev** [comment]
![image](https://user-images.githubusercontent.com/32202/82835574-bd9a3500-9ec4-11ea-889d-b7e7eb1f746f.png)
These settings cause "the end of time" bug for me.

If I change to 10 minutes every 8 hours, the bug no longer occurs.

**Comment by proginosko** [comment]
What's happening in the first block set? What happens if you disable the first block set -- does the bug still occur?

**Comment by kylestratis** [comment]
Ran into this today, only one blockset. Changing (and changing back) the time period (10 minutes within an hour to 10 minutes within 1.5 hours) resets the time limit, but once the sites are blocked again it again is "until the end of time." Disabling and re-enabling the add-on does nothing. 

This is also in Firefox.

**Comment by kylestratis** [comment]
Also, this message appears to be false. After an hour, the sites are unblocked for 10 minutes, as set in the settings.

**Comment by NickWoodward** [comment]
I get this bug too when refreshing the page. Backing out for me works

**Comment by proginosko** [comment]
This was fixed in version 1.5.8.

**Comment by DanielAdari** [comment]
@proginosko 

I'm on Firefox on 1.7.2 and still getting this, after the block time has ended, when refreshing im shown the "the end of time" message but clicking the link / navigating back works.

I have a block set everyday on 2200-2400,0000-0600 and for all sites (`*`) this causes all tabs to become the LB block page and i need to go into each and navigate back / click the link.

**Comment by proginosko** [comment]
> I'm on Firefox on 1.7.2 and still getting this, after the block time has ended, when refreshing im shown the "the end of time" message but clicking the link / navigating back works.
> 
> I have a block set everyday on 2200-2400,0000-0600 and for all sites (`*`) this causes all tabs to become the LB block page and i need to go into each and navigate back / click the link.

I'm not sure what the issue is here. If you refresh the blocking page, you're obviously going to get the blocking page again! To access the blocked page once the blocking period has ended, simply click the link on the blocking page. Alternatively, set the option "Attempt to reload blocked page every __ seconds (only applies to default page)" to something like 10 or 15 seconds.

**Comment by DanielAdari** [comment]
That's cool! I did not know this option existed, tried and it solved my problem :)
Thank you for your work!
