### ISSUE TITLE
I can't "save options & close" successfully

### ISSUE THREAD

**Issue by nad53** [proginosko/LeechBlockNG#98]
Hey greetings sir, I'm the guy who posted you this same message in your LeechBlock extension reviews  in Firefox's website.

"In firefox 66.0.2 I cannot update settings with the option " save & close " ... For some reason once has been closed up I can still joining blocked sites ... Can you actually check if this is happening ? I would appreciate if can be fixed up... Great add-on by the way. I would appreciate if you can answer me, thanks!"

I used to apply this option quite often but since like a week have been happening and it doesn't work even if I remove and adding again the same extension.

Thank you for answering and any help you could bring to fix this issue.

**Comment by proginosko** [comment]
Does the options page close when you click "Save Options & Close"?

**Comment by nad53** [comment]
> 
> 
> Does the options page close when you click "Save Options & Close"?

Yes, she does. But it does save at all. It used to do it perfectly until like 1 week ago.

**Comment by proginosko** [comment]
Okay, try this:

1. Go to Options.
2. Add #test to the list of sites in one of the block sets.
3. Save Options & Close.
4. Go back to Options.

Does #test appear in the list of sites? At this point I need to find out whether the options are being saved at all.

**Comment by nad53** [comment]
> 
> 
> Okay, try this:
> 
>     1. Go to Options.
> 
>     2. Add #test to the list of sites in one of the block sets.
> 
>     3. Save Options & Close.
> 
>     4. Go back to Options.
> 
> 
> Does #test appear in the list of sites? At this point I need to find out whether the options are being saved at all.

Didn't save at all. I have just recently tested a 32bits notebook in windows 10 too and it doesn't save it by any means.

Pretty much I set a password to join options + blocking sites all day long + everyday. If I ever set to default everything, then still doesn't work " save & close ".

**Comment by greendost** [comment]
@nad53 Glad to see that there is a ticket filed. Just wanted to "second" the issue - I am also observing this same problem with "save options and close".  However, "save options" does work, and I can manually close.  This looks like a recently introduced defect.

**Comment by proginosko** [comment]
Yikes, you're right. I can reproduce it myself. I will get this fixed ASAP.

**Comment by nad53** [comment]
> 
> 
> Yikes, you're right. I can reproduce it myself. I will get this fixed ASAP.

You are actually the best buddy. Thank you for answering and this great add-on overall.

**Comment by proginosko** [comment]
Fixed in v0.9.10.1. Should be available on AMO now or soon. Go to Add-ons Manager > Extensions and select Check for Updates from Tools menu (cog icon).

**Comment by nad53** [comment]
> 
> 
> Fixed in v0.9.10.1. Should be available on AMO now or soon. Go to Add-ons Manager > Extensions and select Check for Updates from Tools menu (cog icon).

Fixed up. Amazing developer.

**Comment by greendost** [comment]
@proginosko Thanks for the quick fix!  

One thing though - it seems that on some occasions, it still is not saving for me when I select "save options and close".  So sometimes it saves, and sometimes it doesn't, when I make a change to an entry in the field "Enter the domain names of the sites to block (one item per line):"

I did update to v0.9.10.1. I'll take a look at it further tomorrow, maybe I need to restart my browser.

**Comment by proginosko** [comment]
Okay, let me know if the problem keeps occurring.

**Comment by greendost** [comment]
I just ran a test toggling a url - between mail.yahoo.com and mail.yahoo1.com (to disable blocker) ten times.  It saved once, and the other nine times it failed to save.  It did save successfully on the 11th try.

Details:
10 attempts made, so 10% save rate in this run.
Steps: Select "L" Leechblock badge -> Options -> Make change -> Save options and close
1) mail.yahoo.com -> mail.yahoo1.com  Fail
2) mail.yahoo.com -> mail.yahoo1.com  Pass
3 - 10) mail.yahoo1.com -> mail.yahoo.com  Fail

It could be a timing issue, or maybe something specific to my browser / machine setup.  In general, I don't do this too often, so definitely not an urgent issue, but maybe something to keep in mind if anyone else has this issue.  Thanks.

**Comment by proginosko** [comment]
Hmm. I'd like to get to the bottom of this. Which OS are you using? Which version of Firefox?

Try opening the Browser Console (Ctrl+Shift+J) and see if any errors come up when you save options and close. (You can filter the console output so that only error messages are shown.)

**Comment by greendost** [comment]
Sure, I am on Mac High Sierra 10.13.6, Firefox 66.0.2.  
In the browser console, I noticed this message when I tried "save options and close":

> Promise rejected after context unloaded: TypeError: can't access dead object
options.js:160

> saveOptions moz-extension://45653ec2-eec7-284e-91aa-9dbcbb0bdd0b/options.js:160

**Comment by proginosko** [comment]
Thanks, that's very helpful. The first error message pinpoints the problem. (I don't think the second has anything to do with LB.) Can you confirm for me that you're running v0.9.10.1 of LB? Go to the About tab on options page to confirm.

**Comment by greendost** [comment]
Sure, just confirmed from the "about tab":
> Version: 0.9.10.1

**Comment by proginosko** [comment]
Is the problem still occurring?

**Comment by nad53** [comment]
> 
> 
> Is the problem still occurring?

Haven't had this problem to me since was fixed up. Regards

**Comment by greendost** [comment]
> Is the problem still occurring?

The problem is still occurring for me - "save options and close" doesn't register the save.  But "save options" does work, and I can manually close the tab.

**Comment by matkoniecz** [comment]
Still present in Version: 0.9.11 for me. Both on Windows 7 and Linux (Ubuntu 16.04).

**Comment by proginosko** [comment]
> Still present on both on Windows 7 and Linux (Ubuntu 16.04). In Linux I certainly have version 0.9.11.

Can you confirm that you get the same error as @greendost in the browser console?

**Comment by matkoniecz** [comment]
Yes (at least on Linux, I may check also on Windows if it would be useful).

> Promise resolved after context unloaded
>options.js:160
>    saveOptions moz-extension://d5357ded-9549-4022-9e34-978f3df2749d/options.js:160

**Comment by proginosko** [comment]
I've made some further changes that I hope will resolve this problem. However, I haven't been able to reproduce the problem on my system. The changes will be included in the next release, but if you want to try a beta version you can download it here:

http://www.proginosko.com/files/lbng/leechblock_ng-1.0b1-an+fx.xpi

This beta version includes a couple of new features (customize number of block sets, apply filter instead of blocking page).

**Comment by matkoniecz** [comment]
What I need to do to allow installation? FF proudly announces that it was blocked, I have `xpinstall.signatures.required` and `xpinstall.whitelist.required` set to `false` already.

**Comment by proginosko** [comment]
Hmm. Not sure. I changed the protocol to HTTPS, so see if that fixes it. Otherwise, you might have to copy and paste the URL into your location bar.

**Comment by matkoniecz** [comment]
Not sure whatever https or restart fixed it but I now installed and:

- thanks for ability to customize number of block sets! Limit of six used to be quite frustrating in past for me.

- I can confirm that on my linux browser this problem no longer exists

**Comment by proginosko** [comment]
Great! Thanks for your help in testing the fix.

Note that when the new version is released you'll need to manually install it from AMO. (It won't be automatically installed because you now have a non-AMO beta version installed.)

**Comment by matkoniecz** [comment]
Thanks for reminded, I reinstalled standard version to avoid forgetting about it. And thanks for developing this addon!

**Comment by matkoniecz** [comment]
It is now fixed also in released version, I think that this issue may be closed now.
